fix double dictation process bug, add push-to-dictate option
cboiangiu/decky-dictation pull request #10
Opened 2024-07-04 18:49 UTC by grimkor

PR for #9

* Fixes double-dictation bug by storing the subprocess on the class and checking against it before running a new one. 
* Adds push-to-dictate with the L5 button held down to start this feature. Has a toggle in the plugin menu as well as updated "How to" text for the user.

2024-07-04 20:33 UTC, cboiangiu requested changes

2024-07-04 20:33 UTC, cboiangiu commented on pnpm-lock.yaml
please remove this file. keeping `lockfileVersion: '6.0'` for now

2024-07-04 20:35 UTC, cboiangiu commented on pnpm-lock.yaml
Changes looking good otherwise 👍

2024-07-04 20:41 UTC, cboiangiu commented
Ideally, https://github.com/cboiangiu/decky-dictation/issues/11 should be addressed separately as well at some point, in order to provide a good use experience. Added the issue for visibility. Thank you for your contribution!

2024-07-05 07:25 UTC, grimkor commented on pnpm-lock.yaml
Reverted the lock to main

2024-07-05 08:06 UTC, cboiangiu approved these changes

2024-07-05 08:08 UTC, merged